/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DepartmentInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Department = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const EmploymentStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'OnLeave' : IDL.Null,
});
export const ContractType = IDL.Variant({
  'CDD' : IDL.Null,
  'CDI' : IDL.Null,
  'Internship' : IDL.Null,
  'PartTime' : IDL.Null,
  'Freelance' : IDL.Null,
});
export const HRRole = IDL.Variant({
  'HRAdmin' : IDL.Null,
  'Employee' : IDL.Null,
  'HRManager' : IDL.Null,
  'Direction' : IDL.Null,
  'Manager' : IDL.Null,
});
export const EmployeeInput = IDL.Record({
  'status' : EmploymentStatus,
  'contractType' : ContractType,
  'hrRole' : HRRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'departmentId' : IDL.Opt(IDL.Nat),
  'firstName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'status' : EmploymentStatus,
  'createdAt' : IDL.Int,
  'contractType' : ContractType,
  'hrRole' : HRRole,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'phone' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
  'lastName' : IDL.Text,
  'departmentId' : IDL.Opt(IDL.Nat),
  'firstName' : IDL.Text,
});
export const EmployeeStatusSummary = IDL.Record({
  'onLeave' : IDL.Nat,
  'total' : IDL.Nat,
  'active' : IDL.Nat,
  'inactive' : IDL.Nat,
});
export const DepartmentStat = IDL.Record({
  'departmentName' : IDL.Text,
  'employeeCount' : IDL.Nat,
  'departmentId' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'statusSummary' : EmployeeStatusSummary,
  'departmentStats' : IDL.Vec(DepartmentStat),
});
export const DepartmentWithCount = IDL.Record({
  'id' : IDL.Nat,
  'employeeCount' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const EmployeeFilter = IDL.Record({
  'status' : IDL.Opt(EmploymentStatus),
  'search' : IDL.Opt(IDL.Text),
  'hrRole' : IDL.Opt(HRRole),
  'departmentId' : IDL.Opt(IDL.Nat),
});
export const PaginationParams = IDL.Record({
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
});
export const PaginatedEmployees = IDL.Record({
  'total' : IDL.Nat,
  'employees' : IDL.Vec(Employee),
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDepartment' : IDL.Func([DepartmentInput], [Department], []),
  'createEmployee' : IDL.Func([EmployeeInput], [Employee], []),
  'deleteDepartment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteEmployee' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDepartment' : IDL.Func([IDL.Nat], [IDL.Opt(Department)], ['query']),
  'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDepartments' : IDL.Func([], [IDL.Vec(DepartmentWithCount)], ['query']),
  'listEmployees' : IDL.Func(
      [EmployeeFilter, PaginationParams],
      [PaginatedEmployees],
      ['query'],
    ),
  'setEmployeeProfilePicture' : IDL.Func(
      [IDL.Nat, ExternalBlob],
      [IDL.Bool],
      [],
    ),
  'updateDepartment' : IDL.Func(
      [IDL.Nat, DepartmentInput],
      [IDL.Opt(Department)],
      [],
    ),
  'updateEmployee' : IDL.Func(
      [IDL.Nat, EmployeeInput],
      [IDL.Opt(Employee)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DepartmentInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Department = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const EmploymentStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'OnLeave' : IDL.Null,
  });
  const ContractType = IDL.Variant({
    'CDD' : IDL.Null,
    'CDI' : IDL.Null,
    'Internship' : IDL.Null,
    'PartTime' : IDL.Null,
    'Freelance' : IDL.Null,
  });
  const HRRole = IDL.Variant({
    'HRAdmin' : IDL.Null,
    'Employee' : IDL.Null,
    'HRManager' : IDL.Null,
    'Direction' : IDL.Null,
    'Manager' : IDL.Null,
  });
  const EmployeeInput = IDL.Record({
    'status' : EmploymentStatus,
    'contractType' : ContractType,
    'hrRole' : HRRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'departmentId' : IDL.Opt(IDL.Nat),
    'firstName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'status' : EmploymentStatus,
    'createdAt' : IDL.Int,
    'contractType' : ContractType,
    'hrRole' : HRRole,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'phone' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
    'lastName' : IDL.Text,
    'departmentId' : IDL.Opt(IDL.Nat),
    'firstName' : IDL.Text,
  });
  const EmployeeStatusSummary = IDL.Record({
    'onLeave' : IDL.Nat,
    'total' : IDL.Nat,
    'active' : IDL.Nat,
    'inactive' : IDL.Nat,
  });
  const DepartmentStat = IDL.Record({
    'departmentName' : IDL.Text,
    'employeeCount' : IDL.Nat,
    'departmentId' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'statusSummary' : EmployeeStatusSummary,
    'departmentStats' : IDL.Vec(DepartmentStat),
  });
  const DepartmentWithCount = IDL.Record({
    'id' : IDL.Nat,
    'employeeCount' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const EmployeeFilter = IDL.Record({
    'status' : IDL.Opt(EmploymentStatus),
    'search' : IDL.Opt(IDL.Text),
    'hrRole' : IDL.Opt(HRRole),
    'departmentId' : IDL.Opt(IDL.Nat),
  });
  const PaginationParams = IDL.Record({
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
  });
  const PaginatedEmployees = IDL.Record({
    'total' : IDL.Nat,
    'employees' : IDL.Vec(Employee),
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDepartment' : IDL.Func([DepartmentInput], [Department], []),
    'createEmployee' : IDL.Func([EmployeeInput], [Employee], []),
    'deleteDepartment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteEmployee' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDepartment' : IDL.Func([IDL.Nat], [IDL.Opt(Department)], ['query']),
    'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDepartments' : IDL.Func([], [IDL.Vec(DepartmentWithCount)], ['query']),
    'listEmployees' : IDL.Func(
        [EmployeeFilter, PaginationParams],
        [PaginatedEmployees],
        ['query'],
      ),
    'setEmployeeProfilePicture' : IDL.Func(
        [IDL.Nat, ExternalBlob],
        [IDL.Bool],
        [],
      ),
    'updateDepartment' : IDL.Func(
        [IDL.Nat, DepartmentInput],
        [IDL.Opt(Department)],
        [],
      ),
    'updateEmployee' : IDL.Func(
        [IDL.Nat, EmployeeInput],
        [IDL.Opt(Employee)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };