/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContractType = { 'CDD' : null } |
  { 'CDI' : null } |
  { 'Internship' : null } |
  { 'PartTime' : null } |
  { 'Freelance' : null };
export interface DashboardStats {
  'statusSummary' : EmployeeStatusSummary,
  'departmentStats' : Array<DepartmentStat>,
}
export interface Department {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
}
export interface DepartmentInput { 'name' : string, 'description' : string }
export interface DepartmentStat {
  'departmentName' : string,
  'employeeCount' : bigint,
  'departmentId' : bigint,
}
export interface DepartmentWithCount {
  'id' : bigint,
  'employeeCount' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
}
export interface Employee {
  'id' : bigint,
  'status' : EmploymentStatus,
  'createdAt' : bigint,
  'contractType' : ContractType,
  'hrRole' : HRRole,
  'email' : string,
  'updatedAt' : bigint,
  'phone' : string,
  'profilePicture' : [] | [ExternalBlob],
  'lastName' : string,
  'departmentId' : [] | [bigint],
  'firstName' : string,
}
export interface EmployeeFilter {
  'status' : [] | [EmploymentStatus],
  'search' : [] | [string],
  'hrRole' : [] | [HRRole],
  'departmentId' : [] | [bigint],
}
export interface EmployeeInput {
  'status' : EmploymentStatus,
  'contractType' : ContractType,
  'hrRole' : HRRole,
  'email' : string,
  'phone' : string,
  'lastName' : string,
  'departmentId' : [] | [bigint],
  'firstName' : string,
}
export interface EmployeeStatusSummary {
  'onLeave' : bigint,
  'total' : bigint,
  'active' : bigint,
  'inactive' : bigint,
}
export type EmploymentStatus = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'OnLeave' : null };
export type ExternalBlob = Uint8Array;
export type HRRole = { 'HRAdmin' : null } |
  { 'Employee' : null } |
  { 'HRManager' : null } |
  { 'Direction' : null } |
  { 'Manager' : null };
export interface PaginatedEmployees {
  'total' : bigint,
  'employees' : Array<Employee>,
  'page' : bigint,
  'pageSize' : bigint,
}
export interface PaginationParams { 'page' : bigint, 'pageSize' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDepartment' : ActorMethod<[DepartmentInput], Department>,
  'createEmployee' : ActorMethod<[EmployeeInput], Employee>,
  'deleteDepartment' : ActorMethod<[bigint], boolean>,
  'deleteEmployee' : ActorMethod<[bigint], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDepartment' : ActorMethod<[bigint], [] | [Department]>,
  'getEmployee' : ActorMethod<[bigint], [] | [Employee]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDepartments' : ActorMethod<[], Array<DepartmentWithCount>>,
  'listEmployees' : ActorMethod<
    [EmployeeFilter, PaginationParams],
    PaginatedEmployees
  >,
  'setEmployeeProfilePicture' : ActorMethod<[bigint, ExternalBlob], boolean>,
  'updateDepartment' : ActorMethod<
    [bigint, DepartmentInput],
    [] | [Department]
  >,
  'updateEmployee' : ActorMethod<[bigint, EmployeeInput], [] | [Employee]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];