/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PaginatedEmployees {
    total: bigint;
    employees: Array<Employee>;
    page: bigint;
    pageSize: bigint;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DepartmentWithCount {
    id: bigint;
    employeeCount: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
}
export interface DashboardStats {
    statusSummary: EmployeeStatusSummary;
    departmentStats: Array<DepartmentStat>;
}
export interface EmployeeStatusSummary {
    onLeave: bigint;
    total: bigint;
    active: bigint;
    inactive: bigint;
}
export interface PaginationParams {
    page: bigint;
    pageSize: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Department {
    id: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    updatedAt: bigint;
}
export interface EmployeeFilter {
    status?: EmploymentStatus;
    search?: string;
    hrRole?: HRRole;
    departmentId?: bigint;
}
export interface Employee {
    id: bigint;
    status: EmploymentStatus;
    createdAt: bigint;
    contractType: ContractType;
    hrRole: HRRole;
    email: string;
    updatedAt: bigint;
    phone: string;
    profilePicture?: ExternalBlob;
    lastName: string;
    departmentId?: bigint;
    firstName: string;
}
export interface DepartmentInput {
    name: string;
    description: string;
}
export interface DepartmentStat {
    departmentName: string;
    employeeCount: bigint;
    departmentId: bigint;
}
export interface EmployeeInput {
    status: EmploymentStatus;
    contractType: ContractType;
    hrRole: HRRole;
    email: string;
    phone: string;
    lastName: string;
    departmentId?: bigint;
    firstName: string;
}
export enum ContractType {
    CDD = "CDD",
    CDI = "CDI",
    Internship = "Internship",
    PartTime = "PartTime",
    Freelance = "Freelance"
}
export enum EmploymentStatus {
    Inactive = "Inactive",
    Active = "Active",
    OnLeave = "OnLeave"
}
export enum HRRole {
    HRAdmin = "HRAdmin",
    Employee = "Employee",
    HRManager = "HRManager",
    Direction = "Direction",
    Manager = "Manager"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createDepartment(input: DepartmentInput): Promise<Department>;
    createEmployee(input: EmployeeInput): Promise<Employee>;
    deleteDepartment(id: bigint): Promise<boolean>;
    deleteEmployee(id: bigint): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getDepartment(id: bigint): Promise<Department | null>;
    getEmployee(id: bigint): Promise<Employee | null>;
    isCallerAdmin(): Promise<boolean>;
    listDepartments(): Promise<Array<DepartmentWithCount>>;
    listEmployees(filter: EmployeeFilter, pagination: PaginationParams): Promise<PaginatedEmployees>;
    setEmployeeProfilePicture(id: bigint, blob: ExternalBlob): Promise<boolean>;
    updateDepartment(id: bigint, input: DepartmentInput): Promise<Department | null>;
    updateEmployee(id: bigint, input: EmployeeInput): Promise<Employee | null>;
}
import type { ContractType as _ContractType, Department as _Department, Employee as _Employee, EmployeeFilter as _EmployeeFilter, EmployeeInput as _EmployeeInput, EmploymentStatus as _EmploymentStatus, ExternalBlob as _ExternalBlob, HRRole as _HRRole, PaginatedEmployees as _PaginatedEmployees, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDepartment(arg0: DepartmentInput): Promise<Department> {
        if (this.processError) {
            try {
                const result = await this.actor.createDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDepartment(arg0);
            return result;
        }
    }
    async createEmployee(arg0: EmployeeInput): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployee(to_candid_EmployeeInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Employee_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployee(to_candid_EmployeeInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Employee_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDepartment(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDepartment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDepartment(arg0);
            return result;
        }
    }
    async deleteEmployee(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDepartment(arg0: bigint): Promise<Department | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDepartment(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDepartment(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployee(arg0: bigint): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listDepartments(): Promise<Array<DepartmentWithCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDepartments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDepartments();
            return result;
        }
    }
    async listEmployees(arg0: EmployeeFilter, arg1: PaginationParams): Promise<PaginatedEmployees> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmployees(to_candid_EmployeeFilter_n32(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_PaginatedEmployees_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmployees(to_candid_EmployeeFilter_n32(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_PaginatedEmployees_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async setEmployeeProfilePicture(arg0: bigint, arg1: ExternalBlob): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setEmployeeProfilePicture(arg0, await to_candid_ExternalBlob_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEmployeeProfilePicture(arg0, await to_candid_ExternalBlob_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateDepartment(arg0: bigint, arg1: DepartmentInput): Promise<Department | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDepartment(arg0, arg1);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDepartment(arg0, arg1);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateEmployee(arg0: bigint, arg1: EmployeeInput): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, to_candid_EmployeeInput_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, to_candid_EmployeeInput_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ContractType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContractType): ContractType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_Employee_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Promise<Employee> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_EmploymentStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmploymentStatus): EmploymentStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_HRRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HRRole): HRRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_PaginatedEmployees_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedEmployees): Promise<PaginatedEmployees> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Department]): Department | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Promise<Employee | null> {
    return value.length === 0 ? null : await from_candid_Employee_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EmploymentStatus;
    createdAt: bigint;
    contractType: _ContractType;
    hrRole: _HRRole;
    email: string;
    updatedAt: bigint;
    phone: string;
    profilePicture: [] | [_ExternalBlob];
    lastName: string;
    departmentId: [] | [bigint];
    firstName: string;
}): Promise<{
    id: bigint;
    status: EmploymentStatus;
    createdAt: bigint;
    contractType: ContractType;
    hrRole: HRRole;
    email: string;
    updatedAt: bigint;
    phone: string;
    profilePicture?: ExternalBlob;
    lastName: string;
    departmentId?: bigint;
    firstName: string;
}> {
    return {
        id: value.id,
        status: from_candid_EmploymentStatus_n20(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        contractType: from_candid_ContractType_n22(_uploadFile, _downloadFile, value.contractType),
        hrRole: from_candid_HRRole_n24(_uploadFile, _downloadFile, value.hrRole),
        email: value.email,
        updatedAt: value.updatedAt,
        phone: value.phone,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.profilePicture)),
        lastName: value.lastName,
        departmentId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.departmentId)),
        firstName: value.firstName
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    employees: Array<_Employee>;
    page: bigint;
    pageSize: bigint;
}): Promise<{
    total: bigint;
    employees: Array<Employee>;
    page: bigint;
    pageSize: bigint;
}> {
    return {
        total: value.total,
        employees: await from_candid_vec_n36(_uploadFile, _downloadFile, value.employees),
        page: value.page,
        pageSize: value.pageSize
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Active: null;
} | {
    OnLeave: null;
}): EmploymentStatus {
    return "Inactive" in value ? EmploymentStatus.Inactive : "Active" in value ? EmploymentStatus.Active : "OnLeave" in value ? EmploymentStatus.OnLeave : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CDD: null;
} | {
    CDI: null;
} | {
    Internship: null;
} | {
    PartTime: null;
} | {
    Freelance: null;
}): ContractType {
    return "CDD" in value ? ContractType.CDD : "CDI" in value ? ContractType.CDI : "Internship" in value ? ContractType.Internship : "PartTime" in value ? ContractType.PartTime : "Freelance" in value ? ContractType.Freelance : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    HRAdmin: null;
} | {
    Employee: null;
} | {
    HRManager: null;
} | {
    Direction: null;
} | {
    Manager: null;
}): HRRole {
    return "HRAdmin" in value ? HRRole.HRAdmin : "Employee" in value ? HRRole.Employee : "HRManager" in value ? HRRole.HRManager : "Direction" in value ? HRRole.Direction : "Manager" in value ? HRRole.Manager : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Promise<Array<Employee>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Employee_n18(_uploadFile, _downloadFile, x)));
}
function to_candid_ContractType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContractType): _ContractType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeFilter_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeFilter): _EmployeeFilter {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeInput): _EmployeeInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_EmploymentStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentStatus): _EmploymentStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_HRRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HRRole): _HRRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: EmploymentStatus;
    contractType: ContractType;
    hrRole: HRRole;
    email: string;
    phone: string;
    lastName: string;
    departmentId?: bigint;
    firstName: string;
}): {
    status: _EmploymentStatus;
    contractType: _ContractType;
    hrRole: _HRRole;
    email: string;
    phone: string;
    lastName: string;
    departmentId: [] | [bigint];
    firstName: string;
} {
    return {
        status: to_candid_EmploymentStatus_n12(_uploadFile, _downloadFile, value.status),
        contractType: to_candid_ContractType_n14(_uploadFile, _downloadFile, value.contractType),
        hrRole: to_candid_HRRole_n16(_uploadFile, _downloadFile, value.hrRole),
        email: value.email,
        phone: value.phone,
        lastName: value.lastName,
        departmentId: value.departmentId ? candid_some(value.departmentId) : candid_none(),
        firstName: value.firstName
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: EmploymentStatus;
    search?: string;
    hrRole?: HRRole;
    departmentId?: bigint;
}): {
    status: [] | [_EmploymentStatus];
    search: [] | [string];
    hrRole: [] | [_HRRole];
    departmentId: [] | [bigint];
} {
    return {
        status: value.status ? candid_some(to_candid_EmploymentStatus_n12(_uploadFile, _downloadFile, value.status)) : candid_none(),
        search: value.search ? candid_some(value.search) : candid_none(),
        hrRole: value.hrRole ? candid_some(to_candid_HRRole_n16(_uploadFile, _downloadFile, value.hrRole)) : candid_none(),
        departmentId: value.departmentId ? candid_some(value.departmentId) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentStatus): {
    Inactive: null;
} | {
    Active: null;
} | {
    OnLeave: null;
} {
    return value == EmploymentStatus.Inactive ? {
        Inactive: null
    } : value == EmploymentStatus.Active ? {
        Active: null
    } : value == EmploymentStatus.OnLeave ? {
        OnLeave: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContractType): {
    CDD: null;
} | {
    CDI: null;
} | {
    Internship: null;
} | {
    PartTime: null;
} | {
    Freelance: null;
} {
    return value == ContractType.CDD ? {
        CDD: null
    } : value == ContractType.CDI ? {
        CDI: null
    } : value == ContractType.Internship ? {
        Internship: null
    } : value == ContractType.PartTime ? {
        PartTime: null
    } : value == ContractType.Freelance ? {
        Freelance: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HRRole): {
    HRAdmin: null;
} | {
    Employee: null;
} | {
    HRManager: null;
} | {
    Direction: null;
} | {
    Manager: null;
} {
    return value == HRRole.HRAdmin ? {
        HRAdmin: null
    } : value == HRRole.Employee ? {
        Employee: null
    } : value == HRRole.HRManager ? {
        HRManager: null
    } : value == HRRole.Direction ? {
        Direction: null
    } : value == HRRole.Manager ? {
        Manager: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
